version: "2"

networks:
  app-tier:
    driver: bridge

services:
  fluent-bit:
    env_file:
      - ./fluentbit.env
    image: amazon/aws-for-fluent-bit:latest
    networks:
      - app-tier
    command: ["--config=/etc/td-agent-bit.conf"]
    volumes:
      - ./td-agent-bit.conf:/etc/td-agent-bit.conf
      - /var/log:/var/log

