version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  fluent-bit:
    environment:
      - FLUENTBIT_IMG=${FLUENTBIT_IMG}
    image: ${FLUENTBIT_IMG}
    networks:
      - app-tier
   # command: ["--config=/etc/td-agent-bit.conf"]
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./plugins.conf:/fluent-bit/etc/plugins.conf
      - ./plugins:/fluent-bit/etc/plugins
      - /var/log:/var/log

